events {}
http {
    server {
        listen 8080;
        server_name localhost;

        # ROTA A: Interface Gráfica (Porta 3000 do Open WebUI)
        location / {
            proxy_pass http://open-webui:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # ROTA B: Padrão OpenAI Compatible (API Restrita)
        location /v1/ {
            if ($http_authorization != "Bearer TokenSeguroDaAula2026") {
                return 401;
            }
            proxy_pass http://ollama:11434;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}